### ISSUE TITLE
invalid elf generated when you use sprintf

### ISSUE THREAD

**Issue by psxdev** [xyzz/vitasdk-buildscripts#4]
Check psp2link code at:
https://github.com/psxdev/psp2link
you will need also:
https://github.com/psxdev/debugnet
vita2d and vita_portlibs from xerpi repository
psp2client on linux/osx after psp2link splash screen is showed

All compiled in osx  with last changes in your newlib and your last pull request in vita-toolchain and vita-headers

when compile psp2link sample if you use sprintf instead sceClibSnprintf
check lines:
https://github.com/psxdev/psp2link/blob/master/sample/file_chooser.c#L195
and 
https://github.com/psxdev/psp2link/blob/master/sample/file_chooser.c#L203

invalid elf is generated and crash loading with rejuvenate. It can't read well the segment 0

output segments with sprintf enabled
Segments:
  Segment 0: vaddr 051c90, size 0x8
    Host address region: 0x10f4e6000 - 0x10f4e6008
    4 bytes into segment (0x10f4e6004): 51c94
    addr of 8 bytes into segment (51c98): 0x10f530c98
    12 bytes into segment offset (0x10f4e600c): -1
    addr of 16 bytes into segment (16): 0x0
  Segment 1: vaddr 008000, size 0x49d0c
    Host address region: 0x10f4e7000 - 0x10f530d0c
    4 bytes into segment (0x10f4e7004): 8004
    addr of 8 bytes into segment (8008): 0x10f4e7008
    12 bytes into segment offset (0x10f4e700c): 12
    addr of 16 bytes into segment (16): 0x10f4e7010
  Segment 2: vaddr 060000, size 0x15400
    Host address region: 0x10f531000 - 0x10f546400
    4 bytes into segment (0x10f531004): 60004
    addr of 8 bytes into segment (60008): 0x10f531008
    12 bytes into segment offset (0x10f53100c): 12
    addr of 16 bytes into segment (16): 0x10f531010

output segments with sceClibSnprintf enabled and run fine

Segments:
  Segment 0: vaddr 008000, size 0x46a14
    Host address region: 0x10c428000 - 0x10c46ea14
    4 bytes into segment (0x10c428004): 8004
    addr of 8 bytes into segment (8008): 0x10c428008
    12 bytes into segment offset (0x10c42800c): 12
    addr of 16 bytes into segment (16): 0x10c428010
  Segment 1: vaddr 060000, size 0x15400
    Host address region: 0x10c46f000 - 0x10c484400
    4 bytes into segment (0x10c46f004): 60004
    addr of 8 bytes into segment (60008): 0x10c46f008
    12 bytes into segment offset (0x10c46f00c): 12
    addr of 16 bytes into segment (16): 0x10c46f010

Do you know where can be the problem?

**Comment by xyzz** [comment]
Do you have a minimal example that still causes the issue? Can you also upload full uvloader log for both valid and invalid velfs and also valid and invalid build .elf, .velf.

**Comment by psxdev** [comment]
I will prepare a simple example tomorrow and upload logs from both.

**Comment by xyzz** [comment]
I think this looks like you're using old UVLoader, can you try compiling the latest from git?

**Comment by psxdev** [comment]
update to last uvloader.bin load homebrew fine but printf output is not showed
code:

```
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <stdlib.h>
#include <psp2/types.h>
#include <sys/syslimits.h>
#include <psp2/ctrl.h>
#include <psp2/moduleinfo.h>
#include <psp2/kernel/processmgr.h>
#include <psp2/io/fcntl.h>
#include <psp2/io/dirent.h>
```

#with this main no printf output are shown in log

```
int main()
{
    char new_path[PATH_MAX];
    char one_string[PATH_MAX]="/usr/local";
    char two_string[PATH_MAX]="name";


    printf("Before sprintf\n");
    sprintf(new_path,"%s/%s", one_string, two_string);
    printf("After sprintf %s\n",new_path);
    while(1)
    {

    }


}
```

output was:
Vita] uvloader.c:246 Homebrew running...
[Vita]
[Vita]
[Vita] uvloader.c:246 Homebrew running...

no output from printf  as you can see

#with this main 

```
int main()
{
    char new_path[PATH_MAX];
    char one_string[PATH_MAX]="/usr/local";
    char two_string[PATH_MAX]="name";


    uvl_printf("Before sprintf\n");
    sprintf(new_path,"%s/%s", one_string, two_string);
    uvl_printf("After sprintf %s\n",new_path);
    while(1)
    {

    }


}
```

output was:
Vita] uvloader.c:246 Homebrew running...
[Vita]
[Vita]
[Vita] uvloader.c:246 Homebrew running...
[Vita] Before sprintf
[Vita]
[Vita]
[Vita] Before sprintf
[Vita] After sprintf /usr/local/name
[Vita]
[Vita]
[Vita] After sprintf /usr/local/name

#another test more

```
int main()
{
    char new_path[PATH_MAX];
    char one_string[PATH_MAX]="/usr/local";
    char two_string[PATH_MAX]="name";


    printf("Before sprintf\n");
    sprintf(new_path,"%s/%s", one_string, two_string);
    uvl_printf("After sprintf %s\n",new_path);
    while(1)
    {

    }


}
```

output was:
[Vita] uvloader.c:246 Homebrew running...
[Vita]
[Vita]
[Vita] uvloader.c:246 Homebrew running...
[Vita] After sprintf /usr/local/name
[Vita]
[Vita]
[Vita] After sprintf /usr/local/name

first printf output where is it?

to avoid all these problems i like more use my debugnet library to use customized log over udp. 

Why logs are duplicated on output?

**Comment by xyzz** [comment]
printf won't work, use uvl_printf. The log output is not my issue but VitaDefiler's most likely.

**Comment by psxdev** [comment]
ok  i will use debugnet instead. Thanks for your help. Issue fixed.
